# Generated by Django 4.2.2 on 2023-08-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_ingreso',
            new_name='fecha_actualizacion',
        ),
    ]
